/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Applink: typeof import('./src/components/Applink.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    EventCardSm: typeof import('./src/components/EventCardSm.vue')['default']
    EventFeatured: typeof import('./src/components/EventFeatured.vue')['default']
    EventFilter: typeof import('./src/components/EventFilter.vue')['default']
    EventInfinite: typeof import('./src/components/EventInfinite.vue')['default']
    EventsUpcoming: typeof import('./src/components/EventsUpcoming.vue')['default']
    ImageManager: typeof import('./src/components/ImageManager.vue')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NameCard: typeof import('./src/components/NameCard.vue')['default']
    NoItems: typeof import('./src/components/NoItems.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    PageTitle2: typeof import('./src/components/PageTitle2.vue')['default']
    ProgressLoader: typeof import('./src/components/ProgressLoader.vue')['default']
    ReactionButtons: typeof import('./src/components/ReactionButtons.vue')['default']
    RemoveEntity: typeof import('./src/components/RemoveEntity.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    VAnimated: typeof import('./src/components/v-animated.vue')['default']
    WishlistCard: typeof import('./src/components/WishlistCard.vue')['default']
  }
}
