/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'landing': RouteRecordInfo<'landing', '/', Record<never, never>, Record<never, never>>,
    'pageSlug': RouteRecordInfo<'pageSlug', '/:pageSlug', { pageSlug: ParamValue<true> }, { pageSlug: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    'adminDashboard': RouteRecordInfo<'adminDashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/auth/register', Record<never, never>, Record<never, never>>,
    'resetPassword': RouteRecordInfo<'resetPassword', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    'signin': RouteRecordInfo<'signin', '/auth/signin', Record<never, never>, Record<never, never>>,
    'signout': RouteRecordInfo<'signout', '/auth/signout', Record<never, never>, Record<never, never>>,
    'blog': RouteRecordInfo<'blog', '/blog', Record<never, never>, Record<never, never>>,
    'blogSingle': RouteRecordInfo<'blogSingle', '/blog/:id/single', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'browse': RouteRecordInfo<'browse', '/browse', Record<never, never>, Record<never, never>>,
    '/event/': RouteRecordInfo<'/event/', '/event', Record<never, never>, Record<never, never>>,
    'eventSingle': RouteRecordInfo<'eventSingle', '/event/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'eventEdit': RouteRecordInfo<'eventEdit', '/event/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'eventAdd': RouteRecordInfo<'eventAdd', '/event/add', Record<never, never>, Record<never, never>>,
    'favorite': RouteRecordInfo<'favorite', '/favorite', Record<never, never>, Record<never, never>>,
    'friends': RouteRecordInfo<'friends', '/friends', Record<never, never>, Record<never, never>>,
    'friendsInvite': RouteRecordInfo<'friendsInvite', '/friends/invite', Record<never, never>, Record<never, never>>,
    'notFound': RouteRecordInfo<'notFound', '/not-found', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    '/wall/': RouteRecordInfo<'/wall/', '/wall', Record<never, never>, Record<never, never>>,
    'wall': RouteRecordInfo<'wall', '/wall/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'wishlist': RouteRecordInfo<'wishlist', '/wishlist', Record<never, never>, Record<never, never>>,
    'wishlistSingle': RouteRecordInfo<'wishlistSingle', '/wishlist/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'wishlistEdit': RouteRecordInfo<'wishlistEdit', '/wishlist/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'wishlistAdd': RouteRecordInfo<'wishlistAdd', '/wishlist/add', Record<never, never>, Record<never, never>>,
  }
}
